---
title: "Shiny Project README - Wisconsin Police Stops 2011 - 2015"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary

The goal of this project was exploratory data analysis of the Wisconsin Police Stops dataset, made publicly available by the Stanford Open Policing Project at <https://openpolicing.stanford.edu/>.

Law enforcement agencies in the United States have taken efforts in recent decades to make enforcement data more widely available. Such efforts have resulted in increased transparency into the country's criminal justice system, especially with regard to institutional bias. Enforcement data can also be used to study trends and identify areas of potential improvement.

This study looks at seasonality by month and missingness of racial observations in recent years. It is supplemented by an RShiny web app, which can be found here:

RShiny App: <https://pmasiphelps.shinyapps.io/wisconsinshinyproject/>

A pdf of the presentation prepared in conjunction with this RShiny app can be found in the associated Github repository.

Feel free to contact me with any questions.

Patrick Masi-Phelps
