##ui.R##
##Patrick Masi-Phelps##

library(shiny)
library(shinydashboard)
library(ggplot2)
library(plotly)
library(dplyr)
library(maps)
library(dygraphs)

shinyUI(dashboardPage(
  dashboardHeader(title = "Wisconsin State Patrol Traffic Stops", titleWidth = 400),
  dashboardSidebar(
    #sidebar menu names, icons, and variable names to be used on server side
    sidebarMenu(
      menuItem("Seasonality", 
               tabName = "seasons", 
               icon = icon("snowflake-o"),
               menuSubItem("County Map", tabName = "seasons_counties"),
               menuSubItem("Statewide Bar Graph", tabName = "seasons_state")
               ),
      menuItem("Trends in Racial Variables", 
               tabName = "race", 
               icon = icon("user-o"),
               menuSubItem("Stops by Driver Race", tabName = "race_timeseries"),
               menuSubItem("Missing Race Observations", tabName = "officer_race")
               ),
      menuItem("Stanford Open Policing",
               tabName = "stanford",
               icon = icon("graduation-cap")
               )
      )
  ),
  
  dashboardBody(
    tabItems(
      #contents of the page associated with each tab
      tabItem(tabName = "seasons_counties",
              h2("Seasonality: Police Stops by Month"),
              h4("Heatmap by County: How Does Each Month Compare to an Average Month?"),
              fluidRow(sliderInput("mnth_selected",    
                          "Select Month to Display",
                          month_choice, 
                          value = 1, max = 12, min = 1, 
                          step = 1, ticks = FALSE, animate = TRUE)),
              fluidRow(infoBoxOutput("avgBox", width = 12)),
              fluidPage(plotlyOutput("map"), height = 600, width = "100%"),
              fluidRow(infoBoxOutput("maxBox"),
                       infoBoxOutput("minBox"))
      ),
    
      tabItem(tabName = "seasons_state",
              h2("Seasonality: Police Stops by Month"),
              h4("State-wide"),
              fluidRow(plotlyOutput("statemonthbar", width = 1000, height = 500))
      ),
    
      tabItem(tabName = "race_timeseries",
              h2("Time Series: Police Stops by Race (of Driver)"),
              fluidRow(
                box(width = 12,
                    dygraphOutput("raceline"))
              )
      ),
    
      tabItem(tabName = "officer_race",
              h2("Missing Race Observations by Officer"),
              h4("Heat Map of How Officers Record Race Information"),
              fluidRow(
                box(width = 12,
                    plotOutput("officer_raceheatmap"))
              ),
              h6("This heat map was generated by calculating the percentage of stops made by each unique officer in a given month, where the officer did not record information about the driver's race.
                Lighter blue areas mean more officers recorded that percentage of race observations for their stops that month.
                Most officers had zero missing race observations in 2011, while in late 2014 and 2015, the State Patrol was largely split between officers who did not record race information for any stops and those who recorded race information for all stops.")
      ),
      #this page is to link the user to the Stanford Open Policing Project, which was integral to this project
      tabItem(tabName = "stanford",
              h2("The Stanford Open Policing Project"),
              h5("This Shiny application was inspired by The Stanford Open Policing Project and made use of its publicly available traffic stop data 
                 For more information, please visit https://openpolicing.stanford.edu/"))
      
    )
  )
))
